esw_es8328_codec-objs := es8328-i2c.o es8328.o

obj-$(CONFIG_ESWIN_SND_ES8388_CODEC) += esw_es8328_codec.o

esw_tlv320aic3106_codec-objs := tlv320aic3x-i2c.o tlv320aic3x.o

obj-$(CONFIG_ESWIN_SND_TLV320AIC3106_CODEC) += esw_tlv320aic3106_codec.o
