##Common catapult directives from Document Version 1.1.2 
directive set /$block/SwRegister.sw_vcmd_hw_id:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_hw_version:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_hw_build_date:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_abn_int_src_vcd_mmu:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_abn_int_src_vcd_l2cache:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_abn_int_src_vcd_dec400:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_abn_int_src_vcd:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_abn_int_src_cutree_mmu:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_abn_int_src_vce_mmu:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_abn_int_src_vce_l2cache:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_abn_int_src_vce_dec400:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_abn_int_src_cutree:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_abn_int_src_vce:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_norm_int_src_vcd_mmu:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_norm_int_src_vcd_l2cache:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_norm_int_src_vcd_dec400:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_norm_int_src_vcd:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_norm_int_src_cutree_mmu:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_norm_int_src_vce_mmu:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_norm_int_src_vce_l2cache:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_norm_int_src_vce_dec400:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_norm_int_src_cutree:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_norm_int_src_vce:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_exe_cmdbuf_count:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_executing_cmd:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_executing_cmd_msb:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_axi_total_ar_len:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_axi_total_r:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_axi_total_ar:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_axi_total_r_last:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_axi_total_aw_len:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_axi_total_w:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_axi_total_aw:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_axi_total_w_last:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_axi_total_b:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_axi_ar_valid:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_axi_ar_ready:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_axi_r_valid:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_axi_r_ready:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_axi_aw_valid:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_axi_aw_ready:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_axi_w_valid:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_axi_w_ready:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_axi_b_valid:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_axi_b_ready:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_work_state:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_axi_clk_gate_disable:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_master_out_clk_gate_disable:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_core_clk_gate_disable:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_abort_mode:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_reset_core:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_reset_all:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_start_trigger:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_irq_intcmd:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_irq_jmpp:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_irq_jmpd:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_irq_reset:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_irq_abort:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_irq_cmderr:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_irq_timeout:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_irq_buserr:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_irq_endcmd:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_irq_intcmd_en:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_irq_jmpp_en:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_irq_jmpd_en:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_irq_reset_en:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_irq_abort_en:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_irq_cmderr_en:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_irq_timeout_en:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_irq_buserr_en:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_irq_endcmd_en:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_timeout_en:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_timeout_cycles:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_executing_cmd_addr:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_executing_cmd_addr_msb:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_exe_cmdbuf_length:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_cmd_swap:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_max_burst_len:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_axi_id_rd:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_axi_id_wr:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_rdy_cmdbuf_count:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_abn_int_src_vcd_mmu_gate:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_abn_int_src_vcd_l2cache_gate:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_abn_int_src_vcd_dec400_gate:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_abn_int_src_vcd_gate:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_abn_int_src_cutree_mmu_gate:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_abn_int_src_vce_mmu_gate:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_abn_int_src_vce_l2cache_gate:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_abn_int_src_vce_dec400_gate:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_abn_int_src_cutree_gate:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_abn_int_src_vce_gate:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_norm_int_src_vcd_mmu_gate:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_norm_int_src_vcd_l2cache_gate:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_norm_int_src_vcd_dec400_gate:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_norm_int_src_vcd_gate:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_norm_int_src_cutree_mmu_gate:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_norm_int_src_vce_mmu_gate:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_norm_int_src_vce_l2cache_gate:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_norm_int_src_vce_dec400_gate:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_norm_int_src_cutree_gate:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_ext_norm_int_src_vce_gate:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_vcmd_cmdbuf_executing_id:rsc -MAP_TO_MODULE {[DirectInput]}
