# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_ESWIN_MC)				+= eswin_cpuid_hartid_convert.o
obj-$(CONFIG_ESWIN_RSV_MEMBLOCK)		+= eswin_memblock.o
obj-$(CONFIG_ESWIN_CODACACHE_CONTROLLER)	+= codacache/
