#ifndef __M1_VITOP_HEADER__
#define __M1_VITOP_HEADER__

#define M2_VI_TOP

#ifdef M1_VI_TOP
#define VI_SUBSYSTEM_REGISTER_BASE_ADDRESS      0x41000000
#else //M2 Final Design
#define VI_SUBSYSTEM_REGISTER_BASE_ADDRESS      0x51000000
#endif

enum {
	VI_IOCTL_RESET = _IO('r', 0),
	VI_IOCTL_ISP_H_V = _IO('r', 1),

};

struct soc_control_context {
	uint32_t device_idx;
	uint32_t control_value;
};

struct isp_control_HxV {
    uint32_t horizontal;
    uint32_t vertical;
};

// VI Submodule Base Address
#define VI_ISP0_REGISTER_BASE_ADDRESS           (VI_SUBSYSTEM_REGISTER_BASE_ADDRESS + 0x00000)
#define VI_ISP1_REGISTER_BASE_ADDRESS           (VI_SUBSYSTEM_REGISTER_BASE_ADDRESS + 0x10000)
#define VI_DEWARP_REGISTER_BASE_ADDRESS         (VI_SUBSYSTEM_REGISTER_BASE_ADDRESS + 0x20000)
#define VI_TOP_REGISTER_BASE_ADDRESS            (VI_SUBSYSTEM_REGISTER_BASE_ADDRESS + 0x30000)
#define VI_SHUTTER_CTRL_REGISTER_BASE_ADDRESS   (VI_SUBSYSTEM_REGISTER_BASE_ADDRESS + 0x32000)
#define VI_DVP2AXI_REGISTER_BASE_ADDRESS        (VI_SUBSYSTEM_REGISTER_BASE_ADDRESS + 0x34000)
#define VI_SLVS_CTRL0_REGISTER_BASE_ADDRESS     (VI_SUBSYSTEM_REGISTER_BASE_ADDRESS + 0x38000) //0x38000 FPGA use csi_base
#define VI_SLVS_CTRL1_REGISTER_BASE_ADDRESS     (VI_SUBSYSTEM_REGISTER_BASE_ADDRESS + 0x3c000)
#define VI_SLVS_CTRL2_REGISTER_BASE_ADDRESS     (VI_SUBSYSTEM_REGISTER_BASE_ADDRESS + 0x40000)
#define VI_SLVS_CTRL3_REGISTER_BASE_ADDRESS     (VI_SUBSYSTEM_REGISTER_BASE_ADDRESS + 0x44000)
#define VI_SLVS_CTRL4_REGISTER_BASE_ADDRESS     (VI_SUBSYSTEM_REGISTER_BASE_ADDRESS + 0x48000)
#define VI_SLVS_CTRL5_REGISTER_BASE_ADDRESS     (VI_SUBSYSTEM_REGISTER_BASE_ADDRESS + 0x4c000)

#define VI_CSI2_CTRL0_REGISTER_BASE_ADDRESS     (VI_SUBSYSTEM_REGISTER_BASE_ADDRESS + 0x50000)
#define VI_CSI2_CTRL1_REGISTER_BASE_ADDRESS     (VI_SUBSYSTEM_REGISTER_BASE_ADDRESS + 0x60000)
#define VI_CSI2_CTRL2_REGISTER_BASE_ADDRESS     (VI_SUBSYSTEM_REGISTER_BASE_ADDRESS + 0x70000)
#define VI_CSI2_CTRL3_REGISTER_BASE_ADDRESS     (VI_SUBSYSTEM_REGISTER_BASE_ADDRESS + 0x80000)
#define VI_CSI2_CTRL4_REGISTER_BASE_ADDRESS     (VI_SUBSYSTEM_REGISTER_BASE_ADDRESS + 0x90000)
#define VI_CSI2_CTRL5_REGISTER_BASE_ADDRESS     (VI_SUBSYSTEM_REGISTER_BASE_ADDRESS + 0xa0000)

#define VI_COMBO_PHY0_REGISTER_BASE_ADDRESS     (VI_SUBSYSTEM_REGISTER_BASE_ADDRESS + 0xc0000)
#define VI_COMBO_PHY1_REGISTER_BASE_ADDRESS     (VI_SUBSYSTEM_REGISTER_BASE_ADDRESS + 0xe0000)
#define VI_COMBO_PHY2_REGISTER_BASE_ADDRESS     (VI_SUBSYSTEM_REGISTER_BASE_ADDRESS + 0x100000)
#define VI_COMBO_PHY3_REGISTER_BASE_ADDRESS     (VI_SUBSYSTEM_REGISTER_BASE_ADDRESS + 0x120000)
#define VI_COMBO_PHY4_REGISTER_BASE_ADDRESS     (VI_SUBSYSTEM_REGISTER_BASE_ADDRESS + 0x140000)
#define VI_COMBO_PHY5_REGISTER_BASE_ADDRESS     (VI_SUBSYSTEM_REGISTER_BASE_ADDRESS + 0x160000)

// Should be confirmed in M2
#define VI_TOP_PHY_CONNECT_MODE                 0x00
#define VI_TOP_PHY_MODE_OFFSET                  0x0
// #define VI_TOP_PHY_MODE0_8LANE_4LANE            0x0
// #define VI_TOP_PHY_MODE1_8LANE_2LANEX2          0x1
// #define VI_TOP_PHY_MODE2_4LANEX3                0x2
// #define VI_TOP_PHY_MODE3_4LANEX2_2LANEX2        0x3
// #define VI_TOP_PHY_MODE4_4LANE_2LANEX4          0x4
// #define VI_TOP_PHY_MODE1_2LANEX6                0x5
#define VI_TOP_PHY_TPG_CLOCK_MUX_EN_OFFSET      0x3

#define VI_TOP_CONTROLLER_SELECT                0x04
#define VI_TOP_CONTROLLER_CSI0_SEL_OFFSET       0x0
#define VI_TOP_CONTROLLER_CSI1_SEL_OFFSET       0x1
#define VI_TOP_CONTROLLER_CSI2_SEL_OFFSET       0x2
#define VI_TOP_CONTROLLER_CSI3_SEL_OFFSET       0x3
#define VI_TOP_CONTROLLER_CSI4_SEL_OFFSET       0x4
#define VI_TOP_CONTROLLER_CSI5_SEL_OFFSET       0x5
// #define VI_TOP_CONTROLLER_FROM_CSI              0x0
// #define VI_TOP_CONTROLLER_FROM_MULTI            0x1


#define VI_TOP_ISP_DVP_SEL                      0x08
#define VI_TOP_ISP0_DVP0_SEL_OFFSET             0x0
#define VI_TOP_ISP0_DVP1_SEL_OFFSET             0x3
#define VI_TOP_ISP1_DVP0_SEL_OFFSET             0x6
#define VI_TOP_ISP1_DVP1_SEL_OFFSET             0x9
#define VI_TOP_ISP0_DVP2_SEL_OFFSET             0xc
#define VI_TOP_ISP0_DVP3_SEL_OFFSET             0xf
#define VI_TOP_ISP1_DVP2_SEL_OFFSET             0x12
#define VI_TOP_ISP1_DVP3_SEL_OFFSET             0x15
// #define VI_TOP_ISP_DVP_INPUT_CONTROLER0         0x0
// #define VI_TOP_ISP_DVP_INPUT_CONTROLER1         0x1
// #define VI_TOP_ISP_DVP_INPUT_CONTROLER2         0x2
// #define VI_TOP_ISP_DVP_INPUT_CONTROLER3         0x3
// #define VI_TOP_ISP_DVP_INPUT_CONTROLER4         0x4
// #define VI_TOP_ISP_DVP_INPUT_CONTROLER5         0x5
// #define VI_TOP_ISP_DVP_INPUT_DVP0               0x6
// #define VI_TOP_ISP_DVP_INPUT_DVP1               0x7

#define VI_TOP_ISP0_DVP0_SIZE                   0x0c
#define VI_TOP_ISP0_DVP1_SIZE                   0x10
#define VI_TOP_ISP1_DVP0_SIZE                   0x14
#define VI_TOP_ISP1_DVP1_SIZE                   0x18
#define VI_TOP_ISP0_DVP2_SIZE                   0xa4
#define VI_TOP_ISP0_DVP3_SIZE                   0xa8
#define VI_TOP_ISP1_DVP2_SIZE                   0xac
#define VI_TOP_ISP1_DVP3_SIZE                   0xb0
// #define VI_TOP_ISP_DVP_WIDTH_OFFSET           0x0
// #define VI_TOP_ISP_DVP_HEIGHT_OFFSET          0x10

#define VI_TOP_MULTI2ISP_BLANK                  0x1c

#define VI_TOP_MULTI2ISP0_DVP0                  0x20
#define VI_TOP_MULTI2ISP0_DVP1                  0x24
#define VI_TOP_MULTI2ISP1_DVP0                  0x28
#define VI_TOP_MULTI2ISP1_DVP1                  0x2c
#define VI_TOP_MULTI2ISP0_DVP2                  0xb4
#define VI_TOP_MULTI2ISP0_DVP3                  0xb8
#define VI_TOP_MULTI2ISP1_DVP2                  0xbc
#define VI_TOP_MULTI2ISP1_DVP3                  0xc0
// #define VI_TOP_MULTI2ISP_SHIFT_BIT_OFFSET       0x0
// #define VI_TOP_MULTI2ISP_INV_OFFSET             0x8
// #define VI_TOP_MULTI2ISP_VH_GAP_OFFSET          0x9

#define VI_TOP_DISABLE_ISP0                    0x30
#define VI_TOP_DISABLE_ISP1                    0x34
#define VI_TOP_DEWARP_START                    0x38
#define VI_TOP_ON_STREAM_SEL                   0x3c

#define VI_TOP_CLOCK_ENABLE                    0x40
#define VI_TOP_CLOCK_ENABLE_MASKS              0x1fff
#define VI_TOP_DVP2AXI_CLOCK_ENABLED   (1 << 17)
#define VI_TOP_ISP1_DVP3_CLOCK_ENABLED (1 << 16)
#define VI_TOP_ISP1_DVP2_CLOCK_ENABLED (1 << 15)
#define VI_TOP_ISP0_DVP3_CLOCK_ENABLED (1 << 14)
#define VI_TOP_ISP0_DVP2_CLOCK_ENABLED (1 << 13)
#define VI_TOP_CTRL5_DVP_CLOCK_ENABLED (1 << 12)
#define VI_TOP_CTRL4_DVP_CLOCK_ENABLED (1 << 11)
#define VI_TOP_CTRL3_DVP_CLOCK_ENABLED (1 << 10)
#define VI_TOP_CTRL2_DVP_CLOCK_ENABLED (1 << 9)
#define VI_TOP_CTRL1_DVP_CLOCK_ENABLED (1 << 8)
#define VI_TOP_CTRL0_DVP_CLOCK_ENABLED (1 << 7)
#define VI_TOP_ISP1_DVP1_CLOCK_ENABLED (1 << 6)
#define VI_TOP_ISP1_DVP0_CLOCK_ENABLED (1 << 5)
#define VI_TOP_ISP0_DVP1_CLOCK_ENABLED (1 << 4)
#define VI_TOP_ISP0_DVP0_CLOCK_ENABLED (1 << 3)
#define VI_TOP_DW200_CLOCK_ENABLED     (1 << 2)
#define VI_TOP_ISP1_CLOCK_ENABLED      (1 << 1)
#define VI_TOP_ISP0_CLOCK_ENABLED      (1 << 0)


#define VI_TOP_CSI_COMBO_PHY_IDERR              0x44
#define VI_TOP_CMN_INT_EN                       0x48
#define VI_TOP_CMN_INT_MASK                     0x4c
#define VI_TOP_CMN_INT_CLEAR                    0x50
#define VI_TOP_CMN_INT_STATUS                   0x54


#define VI_TOP_MULTI2ISP0_DVP0_STATUS           0x58
#define VI_TOP_MULTI2ISP0_DVP1_STATUS           0x5c
#define VI_TOP_MULTI2ISP1_DVP0_STATUS           0x60
#define VI_TOP_MULTI2ISP1_DVP1_STATUS           0x64
#define VI_TOP_MULTI2ISP0_DVP2_STATUS           0xb4
#define VI_TOP_MULTI2ISP0_DVP3_STATUS           0xb8
#define VI_TOP_MULTI2ISP1_DVP2_STATUS           0xbc
#define VI_TOP_MULTI2ISP1_DVP3_STATUS           0xc0
// #define VI_TOP_MULTI2ISP_VBLANK_ERR_OFFSET      0x0
// #define VI_TOP_MULTI2ISP_HBLANK_ERR_OFFSET      0x10

#define VI_TOP_PHY_PCLK_CFG                     0x68
#define VI_TOP_DVP0_CNT_STATUS                  0x6c
#define VI_TOP_DVP1_CNT_STATUS                  0x70
#define VI_TOP_DVP2_CNT_STATUS                  0x74
#define VI_TOP_DVP3_CNT_STATUS                  0x78
#define VI_TOP_DVP4_CNT_STATUS                  0x7c
#define VI_TOP_DVP5_CNT_STATUS                  0x80

#define VI_TOP_IO_DVP0_CNT_STATUS               0x84
#define VI_TOP_IO_DVP1_CNT_STATUS               0x88

#define VI_TOP_TOISP0_DVP0_CNT_STATUS           0x8c
#define VI_TOP_TOISP0_DVP1_CNT_STATUS           0x90
#define VI_TOP_TOISP1_DVP0_CNT_STATUS           0x94
#define VI_TOP_TOISP1_DVP1_CNT_STATUS           0x98
#define VI_TOP_TOISP0_DVP2_CNT_STATUS           0xc4
#define VI_TOP_TOISP0_DVP3_CNT_STATUS           0xc8
#define VI_TOP_TOISP1_DVP2_CNT_STATUS           0xcc
#define VI_TOP_TOISP1_DVP3_CNT_STATUS           0xd0

#define VI_TOP_TRIG_IO_SEL                      0xa0

#define VI_TOP_ISP_INPUT_LINESIZE_ERR           0xd4
#define VI_TOP_ISP0_DVP0_LINE_SIZE_ERR_OFFSET   0x0
#define VI_TOP_ISP0_DVP1_LINE_SIZE_ERR_OFFSET   0x1
#define VI_TOP_ISP0_DVP2_LINE_SIZE_ERR_OFFSET   0x2
#define VI_TOP_ISP0_DVP3_LINE_SIZE_ERR_OFFSET   0x3
#define VI_TOP_ISP1_DVP0_LINE_SIZE_ERR_OFFSET   0x4
#define VI_TOP_ISP1_DVP1_LINE_SIZE_ERR_OFFSET   0x5
#define VI_TOP_ISP1_DVP2_LINE_SIZE_ERR_OFFSET   0x6
#define VI_TOP_ISP1_DVP3_LINE_SIZE_ERR_OFFSET   0x7


#ifdef M1_VI_TOP
//M1
#define VI_SUBSYSTEM_SCU_BASE_REGISTER          0x42020000
#define VI_SUBSYSTEM_SCU_ISP_RESET              0x0c
#define VI_SUBSYSTEM_SCU_SONY_HDR_MODE          0x14
#define VI_SLVS_CTRL_0_IRQ_NUM (14 + 1)
#define VI_SLVS_CTRL_1_IRQ_NUM (15 + 1) 
#define VI_CSI2_CTRL0_IRQ_NUM (14 + 1)

#define VI_DVP2AXI_DVP0_IRQ_NUM     29
#define VI_DVP2AXI_DVP1_IRQ_NUM     30
#define VI_DVP2AXI_DVP2_IRQ_NUM     31
#define VI_DVP2AXI_DVP3_IRQ_NUM     32
#define VI_DVP2AXI_DVP4_IRQ_NUM     33
#define VI_DVP2AXI_DVP5_IRQ_NUM     34
#define VI_DVP2AXI_ERROR_IRQ_NUM    35
#define VI_DVP2AXI_AFULL_IRQ_NUM    36

#else
#define VI_SUBSYSTEM_SCU_BASE_REGISTER          0x51828000
#define VI_SUBSYSTEM_SCU_ISP_RESET              0x478
// #define VI_SUBSYSTEM_SCU_SONY_HDR_MODE          0x14
#define VI_SLVS_CTRL_0_IRQ_NUM (24 + 1)//(30 + 1) FPGA use csi_irq
#define VI_SLVS_CTRL_1_IRQ_NUM (25 + 1)//(31 + 1)  

#define VI_CSI2_CTRL0_IRQ_NUM (24 + 1)
#define VI_CSI2_CTRL1_IRQ_NUM (25 + 1)
#define VI_CSI2_CTRL2_IRQ_NUM (26 + 1)
#define VI_CSI2_CTRL3_IRQ_NUM (27 + 1)
#define VI_CSI2_CTRL4_IRQ_NUM (28 + 1)
#define VI_CSI2_CTRL5_IRQ_NUM (29 + 1)

#define VI_DVP2AXI_DVP0_IRQ_NUM     (363 + 1)
#define VI_DVP2AXI_DVP1_IRQ_NUM     (364 + 1)
#define VI_DVP2AXI_DVP2_IRQ_NUM     (365 + 1)
#define VI_DVP2AXI_DVP3_IRQ_NUM     (366 + 1)
#define VI_DVP2AXI_DVP4_IRQ_NUM     (367 + 1)
#define VI_DVP2AXI_DVP5_IRQ_NUM     (368 + 1)
#define VI_DVP2AXI_ERROR_IRQ_NUM    (369 + 1)
#define VI_DVP2AXI_AFULL_IRQ_NUM    (370 + 1)
#endif

#endif
