# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_VIDEO_ESWIN_DVP2AXI) += video_dvp2axi.o
video_dvp2axi-objs += dev.o \
			capture.o \
			dvp2axi-luma.o \
			hw.o \
			subdev-itf.o \
			procfs.o \
			dvp2axi-scale.o \
			common.o \
