# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_SOC_ESWIN) += eswin-win2030.dtb \
							eic7700-evb.dtb \
							eic7700-evb-a2.dtb \
							eic7700-evb-a3.dtb \
							eic7700-hifive-premier-p550.dtb \
							eic7702-evb-a1.dtb \
							eic7700-z530.dtb \
							eic7700-d314.dtb \
							eic7702-evb-a1-interleave.dtb \
							eic7702-tb.dtb \
							eic7700-sbc-a1.dtb \
							eic7700-sbc-a1-mipi.dtb\
							eic7700-osm.dtb \
							eic7702-d560.dtb \
							eic7702-d560-interleave.dtb \
							vpu7702-pcie.dtb \
							vpu7702-evb.dtb
obj-$(CONFIG_BUILTIN_DTB) += $(addsuffix .o, $(dtb-y))
