# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_SOC_SIFIVE) += eswin-win2030.dtb \
							eic7700-evb.dtb \
							eic7700-evb-a2.dtb \
							eic7700-hifive-premier-p550.dtb \
							eic7702-evb-a1-d0.dtb \
							eic7702-evb-a1-d1.dtb

obj-$(CONFIG_BUILTIN_DTB) += $(addsuffix .o, $(dtb-y))
