ISP_AE_V3 := 1
EXTRA_CFLAGS += -DISP_AE_V3

ISP_AWB_V3 := 1
EXTRA_CFLAGS += -DISP_AWB_V3

ISP_AF_V3 := 1
EXTRA_CFLAGS += -DISP_AF_V3

ISP_BLS := 1
EXTRA_CFLAGS += -DISP_BLS

ISP_CCM := 1
EXTRA_CFLAGS += -DISP_CCM

ISP_DPCC := 1
EXTRA_CFLAGS += -DISP_DPCC

ISP_GE := 1
EXTRA_CFLAGS += -DISP_GE

ISP_LSC_V3 := 1
EXTRA_CFLAGS += -DISP_LSC_V3

ISP_WB_V1_1 := 1
EXTRA_CFLAGS += -DISP_WB_V1_1

ISP_DG_V1 := 1
EXTRA_CFLAGS += -DISP_DG_V1

ISP_CMPD_20BIT := 1
EXTRA_CFLAGS += -DISP_CMPD_20BIT

ISP_CPROC := 1
EXTRA_CFLAGS += -DISP_CPROC

ISP_EE_V2 := 1
EXTRA_CFLAGS += -DISP_EE_V2

ISP_GC_V2 := 1
EXTRA_CFLAGS += -DISP_GC_V2

ISP_AFM_V1 := 1
EXTRA_CFLAGS += -DISP_AFM_V1

ISP_DMSC_V2 := 1
EXTRA_CFLAGS += -DISP_DMSC_V2

ISP_EXP_V2 := 1
EXTRA_CFLAGS += -DISP_EXP_V2

ISP_WDR_V4 := 1
EXTRA_CFLAGS += -DISP_WDR_V4

ISP_3DNR_V3_1 := 1
EXTRA_CFLAGS += -DISP_3DNR_V3_1

ISP_DPF_V1 := 1
EXTRA_CFLAGS += -DISP_DPF_V1

ISP_HDR_V2_1 := 1
EXTRA_CFLAGS += -DISP_HDR_V2_1
