# SPDX-License-Identifier: GPL-2.0
dtbo-$(CONFIG_SOC_ESWIN) += eic7700-sbc-a1-camera-imx219-2lanes-overlay.dtbo \
							eic7700-sbc-a1-camera-imx219-phy-mode4-overlay.dtbo \
							eic7700-sbc-a1-camera-imx258-overlay.dtbo \
							eic7700-sbc-a1-camera-imx415-no-hdr-overlay.dtbo \
							eic7700-sbc-a1-camera-imx415-hdr-x2-overlay.dtbo \
							eic7700-sbc-a1-camera-imx415-hdr-x3-overlay.dtbo \
							eic7700-sbc-a1-camera-imx586-overlay.dtbo \
							eic7700-sbc-a1-camera-imx708-overlay.dtbo \
							eic7700-sbc-a1-camera-ov5647-overlay.dtbo \
							eic7700-sbc-a1-camera-ov9281-overlay.dtbo \
							eic7700-sbc-a1-camera-imx327-overlay.dtbo \
							eic7700-ce1-camera-imx415-no-hdr-overlay.dtbo \
							eic7700-ce1-camera-imx415-hdr-x2-overlay.dtbo \
							eic7700-ce1-camera-imx415-hdr-x3-overlay.dtbo \
							eic7700-ce1-camera-imx586-overlay.dtbo \
							eic7700-ce1-camera-imx708-overlay.dtbo \
							eic7700-ce1-camera-ov5647-overlay.dtbo \
							eic7700-ce1-camera-ov9281-overlay.dtbo \
							eic7700-ce1-camera-imx219-phy-mode3-overlay.dtbo \
							eic7700-ce1-camera-imx219-phy-mode4-overlay.dtbo \
							eic7700-hifive-premier-p550-ov5647-overlay.dtbo \
							eic7700-hifive-premier-p550-ov9281-overlay.dtbo \
							eic7702-d560-camera-imx415-no-hdr-overlay.dtbo \
							eic7702-d560-camera-imx415-hdr-x2-overlay.dtbo \
							eic7702-d560-camera-imx415-hdr-x3-overlay.dtbo \
							eic7702-d560-camera-imx708-overlay.dtbo \
							eic7702-d560-camera-imx586-overlay.dtbo \
							eic7702-d560-camera-ov9281-overlay.dtbo \
							eic7702-d560-camera-imx219-phy-mode4-overlay.dtbo \
							eic7700-hifive-premier-p550-mipi.dtbo \
							eic7700-d314-mipi.dtbo \
							eic7700-evb-a2-mipi.dtbo \
							eic7700-evb-a3-mipi.dtbo \
							eic7700-evb-a4-mipi.dtbo \
							eic7700-sbc-a1-mipi.dtbo \
							eic7700-ce1-mipi.dtbo \
							eic7700-vela-mipi.dtbo \
							eic7702-d560-die0-mipi.dtbo \
							eic7702-d560-die1-mipi.dtbo
targets += dtbs dtbs_install
targets += $(dtbo-y)
always-y += $(dtbo-y)
clean-files	:= *.dtbo