# SPDX-License-Identifier: GPL-2.0
dtbo-$(CONFIG_SOC_ESWIN) += eic7700-sbc-a1-camera-imx219-2lanes-overlay.dtbo \
							eic7700-sbc-a1-camera-imx258-overlay.dtbo \
							eic7700-sbc-a1-camera-imx415-overlay.dtbo \
							eic7700-sbc-a1-camera-imx415-no-hdr-overlay.dtbo \
							eic7700-sbc-a1-camera-imx415-hdr-x2-overlay.dtbo \
							eic7700-sbc-a1-camera-imx415-hdr-x3-overlay.dtbo \
							eic7700-sbc-a1-camera-imx586-overlay.dtbo \
							eic7700-sbc-a1-camera-imx708-overlay.dtbo \
							eic7700-sbc-a1-camera-ov5647-overlay.dtbo \
							eic7700-sbc-a1-camera-ov9281-overlay.dtbo \
							eic7700-ce1-camera-imx415-overlay.dtbo \
							eic7700-ce1-camera-imx415-no-hdr-overlay.dtbo \
							eic7700-ce1-camera-imx415-hdr-x2-overlay.dtbo \
							eic7700-ce1-camera-imx415-hdr-x3-overlay.dtbo \
							eic7700-ce1-camera-imx586-overlay.dtbo \
							eic7700-ce1-camera-imx708-overlay.dtbo \
							eic7700-ce1-camera-ov5647-overlay.dtbo \
							eic7700-ce1-camera-ov9281-overlay.dtbo \
							eic7700-hifive-premier-p550-ov5647-overlay.dtbo \
							eic7700-hifive-premier-p550-ov9281-overlay.dtbo

targets += dtbs dtbs_install
targets += $(dtbo-y)
always-y += $(dtbo-y)
clean-files	:= *.dtbo