override HOST_PRIMARY_ARCH := host_x86_64
override HOST_32BIT_ARCH := host_i386
override HOST_FORCE_32BIT := -m32
override HOST_ALL_ARCH := host_x86_64 host_i386
override TARGET_PRIMARY_ARCH := target_riscv64
override TARGET_SECONDARY_ARCH :=
override TARGET_ALL_ARCH := target_riscv64
override TARGET_FORCE_32BIT :=
override PVR_ARCH := volcanic
override PVRSRV_DIR := services
override METAG_VERSION_NEEDED := 2.8.1.0.3
override RISCV_VERSION_NEEDED := 1.7.1
override KERNELDIR := /lib/modules/6.6.21-eic7x/build/
override KERNEL_ID := 6.6.21-eic7x
override PVRSRV_MODULE_BASEDIR := /lib/modules/6.6.21-eic7x/extra/
override KERNEL_COMPONENTS := srvkm drm_nulldisp drm_nulldisp
override KERNEL_CROSS_COMPILE := riscv64-unknown-linux-gnu-
override WINDOW_SYSTEM := xorg
override PVRSRV_MODNAME := pvrsrvkm
override PVRHMMU_MODNAME :=
override PVR_BUILD_DIR := eswin_linux
override PVR_BUILD_TYPE := release
override SUPPORT_RGX := 1
override DISPLAY_CONTROLLER := drm_nulldisp
override PVR_SYSTEM := eswin_cpu
override PVR_LOADER :=
override BUILD := release
override SORT_BRIDGE_STRUCTS := 1
override DEBUGLINK := 1
override RGX_BNC := 30.V.408.101
override PVRSRV_ENABLE_XD_MEM := 1
override SUPPORT_LINUX_FDINFO := 1
override PVRSRV_TRACE_ROGUE_EVENTS := 1
override SUPPORT_PHYSMEM_TEST := 1
override RGX_NUM_DRIVERS_SUPPORTED := 1
override RGX_FW_HEAP_OSID_ASSIGNMENT := RGX_FW_HEAP_USES_FIRMWARE_OSID
override VMM_TYPE := stub
override SUPPORT_POWMON_COMPONENT := 1
override RGX_SECONDARY_OS_CLOCK_SOURCE := mono 
override PDVFS_COM_HOST := 1
override PDVFS_COM_AP := 2
override PDVFS_COM_PMC := 3
override PDVFS_COM_IMG_CLKDIV := 4
override PDVFS_COM_SYSREG := 5
override PDVFS_COM := PDVFS_COM_HOST
override SUPPORT_FW_CORE_CLK_RATE_CHANGE_NOTIFY := 1
override PVR_GPIO_MODE_GENERAL := 1
override PVR_GPIO_MODE := PVR_GPIO_MODE_GENERAL
override PVR_HANDLE_BACKEND := idr
override SUPPORT_DMABUF_BRIDGE := 1
override SUPPORT_DI_BRG_IMPL := 1
override SUPPORT_WRAP_EXTMEM := 1
override SUPPORT_NATIVE_FENCE_SYNC := 1
override SUPPORT_DMA_FENCE := 1
override SUPPORT_BUFFER_SYNC := 1
