# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_PHY_ESWIN_CSI2_DPHY) += eswin_csi2_dphy_hw.o
obj-$(CONFIG_PHY_ESWIN_CSI2_DPHY) += eswin_csi2_dphy.o
eswin_csi2_dphy_hw-objs += phy-eswin-csi2-dphy-hw.o
eswin_csi2_dphy-objs += phy-eswin-csi2-dphy.o #phy-eswin-csi2-dphy-hw.o
