# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the eswin vi device drivers.
#

obj-$(CONFIG_VIDEO_ESWIN_DVP2AXI) += dvp2axi/
obj-$(CONFIG_DWC_MIPI_CSI2_HOST) += mipi-csi2/
obj-$(CONFIG_VIDEO_ESWIN_ISP) += isp/
obj-$(CONFIG_PHY_ESWIN_CSI2_DPHY) += mipi-cdphy/
obj-$(CONFIG_VIDEO_ESWIN_VI_TOP) += eswin_vi.o