# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_ESWIN_RSVMEM_HEAP)	+= eswin_rsvmem_heap.o eswin_rsvmem_common.o dmabuf-heap-import-helper.o


ES_RSVMEM_HEADER := drivers/memory/eswin/es_rsvmem_heap/include/linux
